Repository dnd-side-project/dnd-8th-5-frontend, pull requests merged in 2023-08, with the labels that each got.

#117 fix: 키보드 활성화시 사파리 환경에서 까만 화면 발생 오류 해결 (크로스브라우징)
  src/hooks/useInputScroll.ts
  src/pages/login/Login.tsx
  src/pages/roomStart/RoomStart.tsx
Labels: ⚙️ REFACTOR, 🐛 BUG, ⛅️ 우선순위 - 중

#115 fix: 일정 등록 QA 반영
  package.json
  src/assets/icons/reset.svg
  src/components/addButton/AddButton.styles.ts
  src/components/addButton/AddButton.tsx
  src/components/addTimeTable/AddTimeTable.tsx
  src/components/addTimeTable/AddTimeTable.types.ts
  src/components/addTimeTable/Table.tsx
  src/components/resultButton/ResultButton.stories.tsx
  src/pages/addTime/AddTime.tsx
  src/styles/theme.ts
  yarn.lock
Labels: 🐛 BUG, ☀️ 우선순위 - 상

#114 feat: tanstack-query 적용
  package.json
  src/api/auth.ts
  src/api/availableTimes.ts
  src/api/instance.ts
  src/api/result.ts
  src/api/room.ts
  src/assets/data/initialCreateRoomData.ts
  src/assets/data/initialRoomInfoData.ts
  src/atoms/availableBottomSheet.ts
  src/atoms/createRoomAtoms.ts
  src/atoms/recoilRoomAtoms.ts
  src/atoms/recoilUuidAtoms.ts
  src/components/addCalendar/AddCalendar.tsx
  src/components/addTimeTable/AddTimeTable.tsx
  src/components/bottomSheetShare/BottomSheetShare.tsx
  src/components/currentCalendar/CurrentCalendar.tsx
  src/components/header/Header.tsx
  src/components/table/Table.tsx
  src/components/timer/Timer.tsx
  src/constants/QUERY_KEYS.ts
  src/constants/ROUTES.ts
  src/hooks/useFormInput.ts
  src/index.tsx
  src/pages/addTime/AddTime.tsx
  src/pages/current/Current.tsx
  src/pages/invite/Invite.tsx
  src/pages/login/Login.tsx
  src/pages/result/Result.tsx
  src/pages/roomCalendar/RoomCalendar.tsx
  src/pages/roomStart/RoomStart.tsx
  src/pages/roomTimer/RoomTimer.tsx
  src/queries/auth/usePostUserInfo.ts
  src/queries/availableTimes/useGetAvailableTimesByGroup.ts
  src/queries/availableTimes/useGetAvailableTimesByOne.ts
  src/queries/availableTimes/usePutAvailableTimes.ts
  src/queries/result/useGetCandidateTimes.ts
  src/queries/room/useCreateRoom.ts
  src/queries/room/useGetRoomInfo.ts
  src/types/addTime.ts
  src/types/auth.ts
  src/types/result.ts
  src/types/roomInfo.ts
  yarn.lock
Labels: ⚙️ REFACTOR, 🔩 STYLE, 🙈 CHORE, ✨ FEATURE, ☁️ 우선순위 - 하

#119 refactor: 0805 QA 진행
  src/App.tsx
  src/assets/images/background.webp
  src/assets/images/errorBack.webp
  src/assets/images/roomStartBack.webp
  src/assets/images/startBack.webp
  src/components/bottomButton/BottomButton.styles.ts
  src/components/bottomButton/BottomButton.tsx
  src/components/bottomButton/BottomButton.types.ts
  src/components/calendar/Calendar.tsx
  src/components/menu/Menu.tsx
  src/components/resultButton/ResultButton.tsx
  src/constants/ROUTES.ts
  src/hooks/useScrollToTop.ts
  src/pages/404/404.styles.ts
  src/pages/404/404.tsx
  src/pages/current/Current.tsx
  src/pages/login/Login.tsx
  src/pages/roomCalendar/RoomCalendar.styles.ts
  src/pages/roomCalendar/RoomCalendar.tsx
  src/pages/roomStart/RoomStart.styles.ts
  src/pages/roomStart/RoomStart.tsx
  src/pages/roomTimer/RoomTimer.tsx
  src/pages/start/Start.styles.ts
  src/pages/start/Start.tsx
  src/queries/room/useGetRoomInfo.ts
Labels: ⚙️ REFACTOR, 🎨 DESIGN, ✨ FEATURE, ☀️ 우선순위 - 상
