Repository dnd-side-project/dnd-8th-5-frontend, pull requests merged in 2023-06, with the labels that each got.

#70 feat: 초대 페이지 추가
  src/App.tsx
  src/assets/images/calendar.png
  src/assets/images/inviteBack.png
  src/components/bottomSheetShare/BottomSheetShare.tsx
  src/components/header/Header.tsx
  src/pages/invite/Invite.styles.ts
  src/pages/invite/Invite.tsx
  src/pages/login/Login.tsx
Labels: ✨ FEATURE, ☀️ 우선순위 - 상

#75 feat: 메뉴바 구현
  src/assets/icons/headerMenu.svg
  src/assets/icons/menuFavicon.png
  src/assets/icons/menuPlus.svg
  src/assets/images/menuExit.png
  src/assets/images/resultBubble.png
  src/components/header/Header.styles.ts
  src/components/header/Header.tsx
  src/components/menu/Menu.styles.ts
  src/components/menu/Menu.tsx
  src/components/resultButton/ResultButton.tsx
  src/components/timer/Timer.styles.ts
  src/components/timer/Timer.tsx
  src/utils/getCountdown.ts
  src/utils/slideRightAnimation.ts
Labels: ✨ FEATURE, ☀️ 우선순위 - 상

#84 fix: 일정 등록 로직 변경
  src/atoms/availableGuideAtoms.ts
  src/atoms/isTooltipShownAtoms.ts
  src/components/accordion/Accordion.stories.tsx
  src/components/addCalendar/AddCalendar.stories.tsx
  src/components/addTable/AddTable.stories.tsx
  src/components/addTable/AddTable.styles.ts
  src/components/addTable/AddTable.tsx
  src/components/addTable/AddTable.types.ts
  src/components/addTable/Table.styles.ts
  src/components/addTable/Table.tsx
  src/components/addToggle/AddToggle.tsx
  src/components/header/Header.tsx
  src/components/resultOption/Pariticipant.tsx
  src/components/resultOption/SelectParticipants.styles.ts
  src/components/resultOption/SelectParticipants.tsx
  src/components/resultOption/SortTimes.styles.ts
  src/components/resultOption/SortTimes.tsx
  src/components/resultOption/resultOption.types.ts
  src/components/selectParticipants/Pariticipant.tsx
  src/components/selectParticipants/SortTimes.tsx
  src/components/tooltip/Tooltip.styles.ts
  src/components/tooltip/Tooltip.tsx
  src/hooks/useScroll.ts
  src/pages/addTime/AddTime.styles.ts
  src/pages/addTime/AddTime.tsx
  src/pages/addTime/AddTime.types.ts
  src/pages/current/Current.styles.ts
  src/pages/current/Current.tsx
  src/pages/result/Result.styles.ts
  src/pages/result/Result.tsx
  src/utils/currentTableInfo.json
  src/utils/getAddTimeTableInfo.ts
  src/utils/getAllTimeRange.ts
  src/utils/getChunks.ts
  src/utils/getThreeChunks.ts
Labels: ⚙️ REFACTOR, 🐛 BUG, ☀️ 우선순위 - 상

#89 fix: 모바일에서 애니메이션의 잔상이 보이는 문제 해결
  src/components/addToggle/AddToggle.styles.ts
  src/components/progressBar/progressBar.styles.ts
Labels: 🐛 BUG, ☁️ 우선순위 - 하

#87 fix: 6월 22일 QA 수정사항 (방생성 일정등록, 시작페이지, 바텀시트)
  src/components/bottomSheetShare/BottomSheetShare.tsx
  src/components/calendar/Calendar.styles.ts
  src/components/calendar/Calendar.tsx
  src/pages/start/start.styles.ts
Labels: 🐛 BUG, 🎨 DESIGN, ☀️ 우선순위 - 상

#97 fix: QA 진행 사항 반영
  src/atoms/availableDatesAtom.ts
  src/components/addTable/Table.styles.ts
  src/components/bottomSheet/BottomSheet.styles.ts
  src/components/header/Header.tsx
  src/components/menu/Menu.styles.ts
  src/components/option/index.styles.ts
  src/components/option/participantsOption/Pariticipant.tsx
  src/components/option/participantsOption/participantsOption.styles.ts
  src/components/option/participantsOption/participantsOption.tsx
  src/components/option/participantsOption/participantsOption.types.ts
  src/components/option/sortOption/SortTimes.styles.ts
  src/components/option/sortOption/SortTimes.tsx
  src/components/progressBar/ProgressBar.tsx
  src/components/resultOption/SelectParticipants.tsx
  src/components/resultOption/SortTimes.tsx
  src/components/resultOption/resultOption.types.ts
  src/components/setTimer/SetTimer.tsx
  src/components/table/Table.styles.ts
  src/components/timePicker/TimePicker.tsx
  src/pages/current/Current.tsx
  src/pages/login/Login.tsx
  src/pages/result/Result.tsx
  src/pages/roomTimer/RoomTimer.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/utils/getAddTimeTableInfo.ts
  src/utils/getRange.ts
  src/utils/getValidDates.ts
  src/utils/slideAnimation.ts
  src/utils/slideRightAnimation.ts
Labels: ⚙️ REFACTOR, 🎨 DESIGN, ✨ FEATURE, ☀️ 우선순위 - 상
